  GNU nano 2.9.8                                                                                                                                                                      kaf-state.yaml                                                                                                                                                                                 

apiVersion: v1
kind: Service
metadata:
  name: kafka-sv
  namespace: time-series
spec:
  clusterIP: None
  selector:
    app: kafka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: time-series
spec:
  serviceName: kafka-sv
  replicas: 5
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
	app: kafka
    spec:
      containers:
      - name: kafka
        image: node03.st:5000/kafka:prod2.8
        ports:
    	- containerPort: 29092
        - containerPort: 9092
        env:
	    - name: HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: metadata.name
        - name: KAFKA_ADVERTISED_PORT
          value: "9092"
        - name: KAFKA_LISTENERS
          value: "INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "INTERNAL://$(HOSTNAME).kafka-sv:29092,EXTERNAL://$(HOSTNAME).kafka-sv:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
        - name: KAFKA_INTER_BROKER_LISTENER_NAME
          value: INTERNAL
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: zoo1:2181
        - name: KAFKA_CREATE_TOPICS
          value: admintome-test:1:1
        - name: KAFKA_DEFAULT_REPLICATION_FACTOR
          value: "2"







